apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
    app: jira-app
spec:
  containers:
    - name: web
      image: index.docker.io/shahnavedali/jira-app
      ports:
        - containerPort: 3003
