apiVersion: v1
kind: ReplicationController
metadata:
  name: web
  labels:
    name: web
    app: jira-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
        - name: web
          image: shahnavedali/jira-app
          ports:
            - containerPort: 3003
              name: http
              
              protocol: TCP