kind: Service
apiVersion: v1
metadata:
  name: web-time
  labels:
    name: web-time
    app: jira-app-time
spec:
  selector:
    name: web-time 
  type: NodePort
  ports:
   - port: 3003
     nodePort: 30000