apiVersion: v1
kind: ReplicationController
metadata:
  name: web-time
  labels:
    name: web-time
    app: jira-app-time
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: web-time
    spec:
      containers:
        - name: web-time
          image: 62.60.42.82:8123/nshah/jira-kube-log
          ports:
            - containerPort: 3003
              name: http
              
              protocol: TCP